module.exports = {

  AUTH: process.env.AUTH_SERVICE_URL,
  PRODUCT: process.env.PRODUCT_SERVICE_URL,
  ORDER: process.env.ORDER_SERVICE_URL,
  VENDOR: process.env.VENDOR_SERVICE_URL,
  INVENTORY: process.env.INVENTORY_SERVICE_URL,
  RECOMMENDATION: process.env.RECOMMENDATION_SERVICE_URL,
  NOTIFICATION: process.env.NOTIFICATION_SERVICE_URL

};